[package]
edition = "2024"
name = "assignment"
version = "0.1.0"

[dependencies]
borsh = { version = "1.5.7", features = ["derive"] }
serde = {version = "1.0.219", features = ["derive"]}
serde_json = "1.0.140"
