[package]
name = "first-native-solana-program"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "lib"]


[dependencies]
borsh = "1.5.7"
borsh-derive = "1.5.7"
jito-account-traits-derive = "0.0.5"
solana-program = "2.3.0"
